
services:
  - type: web
    name: lora-cafe
    runtime: java
    plan: free

    buildCommand: "./mvnw clean install -DskipTests"
    startCommand: "java -jar target/loracafe-0.0.1-SNAPSHOT.jar"

    envVars:
      - key: MYSQL_URL
        fromSync: false
      - key: MYSQLUSER
        fromSync: false
      - key: MYSQLPASSWORD
        fromSync: false
      - key: SERVER_PORT
        value: 8090